This is makeindex, version 2.15 [MiKTeX 2.9.6630 64-bit] (kpathsea + Thai support).
Scanning style file ./mthesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file mthesis.acn....done (1 entries accepted, 0 rejected).
Sorting entries...done (0 comparisons).
Generating output file mthesis.acr....done (6 lines written, 0 warnings).
Output written in mthesis.acr.
Transcript written in mthesis.alg.
